=== vajanko/mirror-testing-system/trunk/MTS/config/tasks.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT timeline (set|wait|waitfor|if|check|test)*>

<!-- set channel value -->
<!ELEMENT set (behavior?, channel+)>
<!ATTLIST set id ID #IMPLIED>

<!-- wait for a specified period of time -->
<!ELEMENT wait (behavior?)>
<!ATTLIST wait id ID #IMPLIED
               time CDATA #REQUIRED>
<!-- wait for specified value on a specified channel -->
<!ELEMENT waitfor (behavior?, channel+)>
<!ATTLIST waitfor id ID #IMPLIED>

<!-- condition task -->
<!ELEMENT if (behavior?, channel+, then, else?)>
<!ATTLIST if id ID #IMPLIED>
<!ELEMENT then (set|wait|waitfor|if|check|test)>
<!ELEMENT else (set|wait|waitfor|if|check|test)?>

<!-- check (usually presence) test -->
<!ELEMENT check (behavior?)>
<!ATTLIST check id ID #IMPLIED
                testparam NMTOKEN #REQUIRED
                channel NMTOKEN #REQUIRED>

<!-- test -->
<!ELEMENT test (behavior?)>
<!ATTLIST test id ID #IMPLIED
               testtype NMTOKEN #REQUIRED
               testparam NMTOKEN #REQUIRED>

<!-- pair digital channel and its value -->
<!ELEMENT channel EMPTY>
<!-- name: Name of channel - using name from channels configuration file -->
<!-- value: Value of digital channel - only possible values are true or false -->
<!ATTLIST channel name NMTOKEN #REQUIRED
                  value (true|false) #REQUIRED>

<!-- Defines task behavior: which tasks are required to be completed when starting current one and
     which are disallowed to be executed at the same time -->
<!ELEMENT behavior EMPTY>
<!ATTLIST behavior require IDREFS #IMPLIED
                   disallow IDREFS #IMPLIED>

<!ELEMENT task (set|wait|waitfor|if|check|test)>

=== vajanko/mirror-testing-system/branches/mvc/MTS/config/tasks.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE timeline SYSTEM "tasks.dtd">

<!--
  For each test there is a special channel defined: Is{test name}Enabled
-->

<timeline>
  <!-- allow to switch power supply on -->
  <set id="allowPower">
    <channel name="AllowPowerSupply" value="true"/>
  </set>
  <!-- wait for power supply to switched on -->
  <waitfor id="waitForPower">
    <behavior require ="allowPower"/>
    <channel name="IsPowerSupplyOff" value="false"/>
  </waitfor>
  <!-- open device if it is closed -->
  <if id="isUnlocking">
    <behavior require="waitForPower"/>
    <channel name="IsOldMirror" value="true"/>
    <channel name="IsOldLocked" value="true"/>
    <then>
      <set>
        <channel name="LockStrong" value="false"/>
        <channel name="LockWeak" value="false"/>
        <channel name="UnlockWeak" value="true"/>
        <channel name="UnlockStrong" value="true"/>
      </set>
    </then>
    <else>
      <if>
        <channel name="IsOldMirror" value="false"/>
        <channel name="IsLocked" value="true"/>
        <then>
          <set>
            <channel name="LockStrong" value="false"/>
            <channel name="LockWeak" value="false"/>
            <channel name="UnlockWeak" value="true"/>
            <channel name="UnlockStrong" value="true"/>
          </set>
        </then>
      </if>
    </else>
  </if>
  <!-- wait for start button to be pressed and released -->
  <waitfor id="startDown">
    <behavior require="isUnlocking"/>
    <channel name="IsStartPressed" value="true"/>
  </waitfor>
  <waitfor id="startUp">
    <behavior require="startDown"/>
    <channel name="IsStartPressed" value="false"/>
  </waitfor>
  <!-- switch off all lights (from previous sequence) -->
  <set>
    <behavior require="startDown"/>
    <channel name="GreenLightOn" value="false"/>
    <channel name="RedLightOn" value="false"/>
  </set>
  <!-- close device -->
  <set id="lockWeak">
    <behavior require="startUp"/>
    <channel name="LockStrong" value="false"/>
    <channel name="LockWeak" value="true"/>
    <channel name="UnlockWeak" value="false"/>
    <channel name="UnlockStrong" value="false"/>
  </set>
  <!-- wait for device to be closed -->
  <if id="isLocked">
    <behavior require="lockWeak"/>
    <channel name="IsOldMirror" value="true"/>
    <then>
      <waitfor>
        <channel name="IsOldLocked" value="true"/>
      </waitfor>
    </then>
    <else>
      <waitfor>
        <channel name="IsLocked" value="true"/>
      </waitfor>
    </else>
  </if>
  <!-- lock device strongly -->
  <set id="lockStrong">
    <behavior require="isLocked"/>
    <channel name="LockStrong" value="true"/>
  </set>

  <!-- check for mirror presence -->
  <if id="mirrorPresence">
    <behavior require="lockStrong"/>
    <channel name="IsOldMirror" value="true"/>
    <then>
      <check channel="IsOldPowerfoldUp" testparam="MirrorGlass"/>
    </then>
    <else>
      <check channel="IsPowerfoldUp" testparam="MirrorGlass"/>
    </else>
  </if>

  <test id="pulloff" testparam="Pulloff" testtype="PulloffTest">
    <behavior require="mirrorPresence"/>
  </test>
  
  <!-- rubber test -->
  <if id="rubber">
    <behavior require="lockStrong"/>
    <channel name="IsLeftMirror" value="true"/>
    <then>
      <check channel="IsLeftRubberPresent" testparam="Rubber"/>
    </then>
    <else>
      <check channel="IsRightRubberPresent" testparam="Rubber"/>
    </else>
  </if>

  <test id="powerfold" testparam="Powerfold" testtype="PowerfoldTest">
    <behavior require="mirrorPresence" />
  </test>
  <test id="direction" testparam="DirectionLight" testtype="DirectionLightTest">
    <behavior require="mirrorPresence"/>
  </test>
  <test id="heating" testparam="HeatingFoil" testtype="HeatingFoilTest">
    <behavior require="mirrorPresence"/>
  </test>
  
  <!-- move calibrators up -->
  <!-- Only start moving mirror if pull of test has been passed -->
  <!--<if id="moveCalibUp">
    <behavior require="pulloff lockStrong"/>
    <channel name="IsTravelEnabled" value="true"/>
    <then>-->
      <set id="moveCalibUp">
        <behavior require="pulloff lockStrong"/>
        <channel name="MoveDistanceSensorDown" value="false"/>
        <channel name="MoveDistanceSensorUp" value="true"/>
      </set>
    <!--</then>
  </if>-->
  <!-- wait for calibrators to be up -->
  <waitfor id="isCalibUp">
    <behavior require="moveCalibUp"/>
    <channel name="IsDistanceSensorUp" value="true"/>
  </waitfor>
  <!-- wait one second -->
  <wait id="waitSecond" time="00:00:01">
    <behavior require="isCalibUp"/>
  </wait>
  <!-- allow mirror to move -->
  <set id="allowMovement">
    <behavior require="waitSecond"/>
    <channel name="AllowMirrorMovement" value="true"/>
  </set>

  <!-- move mirror galls to all sides -->
  <test id="travelNorth" testparam="TravelNorth" testtype="TravelNorthTest">
    <behavior require="allowMovement"/>
  </test>
  <!-- if travelNorth is disable travelSouth still requires waitSecond to be finished and does not start before -->
  <test id ="travelSouth" testparam="TravelSouth" testtype="TravelSouthTest">
    <behavior require="allowMovement travelNorth"/>
  </test>
  <test id ="travelEast" testparam="TravelEast" testtype="TravelEastTest">
    <behavior require="allowMovement travelSouth"/>
  </test>
  <test id ="travelWest" testparam="TravelWest" testtype="TravelWestTest">
    <behavior require="allowMovement travelEast"/>
  </test>

  <!-- disallow mirror to move -->
  <set id="disallowMovement">
    <behavior require="allowMovement travelNorth travelSouth travelEast travelWest"/>
    <channel name="AllowMirrorMovement" value="false"/>
  </set>
  <!-- move calibrators down -->
  <set id="moveCalibDown">
    <behavior require="disallowMovement"/>
    <channel name="MoveDistanceSensorDown" value="true"/>
    <channel name="MoveDistanceSensorUp" value="false"/>
  </set>
  <!-- wait for calibrators to be down -->
  <waitfor id="isCalibDown">
    <behavior require="moveCalibDown"/>
    <channel name="IsDistanceSensorDown" value="true"/>
  </waitfor>

  <!-- open device --><!-- all tasks are required to be finished -->
  <if id="isLocking">
    <behavior require="isCalibDown powerfold direction heating rubber pulloff"/>
    <channel name="IsOldMirror" value="true"/>
    <channel name="IsOldLocked" value="true"/>
    <then>
      <set>
        <channel name="LockStrong" value="false"/>
        <channel name="LockWeak" value="false"/>
        <channel name="UnlockWeak" value="true"/>
        <channel name="UnlockStrong" value="true"/>
      </set>
    </then>
    <else>
      <if>
        <channel name="IsOldMirror" value="false"/>
        <channel name="IsLocked" value="true"/>
        <then>
          <set>
            <channel name="LockStrong" value="false"/>
            <channel name="LockWeak" value="false"/>
            <channel name="UnlockWeak" value="true"/>
            <channel name="UnlockStrong" value="true"/>
          </set>
        </then>
      </if>
    </else>
  </if>
  <!-- wait for device to be opened -->
  <if>
    <behavior require="isLocking"/>
    <channel name="IsOldMirror" value="true"/>
    <then>
      <waitfor>
        <channel name="IsOldLocked" value="true"/>
      </waitfor>
    </then>
    <else>
      <waitfor>
        <channel name="IsLocked" value="true"/>
      </waitfor>
    </else>
  </if>
</timeline>

=== vajanko/mirror-testing-system/branches/mvc/MTS/config/calibration.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE timeline SYSTEM "tasks.dtd">

<timeline>
  <!-- allow to switch power supply on -->
  <set id="allowPower">
    <channel name="AllowPowerSupply" value="true"/>
  </set>
  <!-- wait for power supply to switched on -->
  <waitfor id="waitForPower">
    <behavior require ="allowPower"/>
    <channel name="IsPowerSupplyOff" value="false"/>
  </waitfor>
  <!-- open device, if it is closed nothing will happen -->
  <set id="unlock1">
    <channel name="LockStrong" value="false"/>
    <channel name="LockWeak" value="false"/>
    <channel name="UnlockWeak" value="true"/>
    <channel name="UnlockStrong" value="true"/>
  </set>
  
  <!-- wait for mirror to be inserted -->
  <if id="waitForMirror">
    <behavior require="unlock1"/>
    <channel name="IsOldMirror" value="true"/>
    <then>
      <waitfor>
        <channel name="IsOldPowerfoldUp" value="true"/>
      </waitfor>
    </then>
    <else>
      <waitfor>
        <channel name="IsPowerfoldUp" value="true"/>
      </waitfor>
    </else>
  </if>
  
  <!-- wait for start button to be pressed and released -->
  <waitfor id="startDown">
    <behavior require="waitForMirror"/>
    <channel name="IsStartPressed" value="true"/>
  </waitfor>
  <waitfor id="startUp">
    <behavior require="startDown"/>
    <channel name="IsStartPressed" value="false"/>
  </waitfor>
  <!-- close device -->
  <set id="lockWeak">
    <behavior require="startUp"/>
    <channel name="LockStrong" value="false"/>
    <channel name="LockWeak" value="true"/>
    <channel name="UnlockWeak" value="false"/>
    <channel name="UnlockStrong" value="false"/>
  </set>
  <!-- wait for device to be closed -->
  <if id="isLocked">
    <behavior require="lockWeak"/>
    <channel name="IsOldMirror" value="true"/>
    <then>
      <waitfor>
        <channel name="IsOldLocked" value="true"/>
      </waitfor>
    </then>
    <else>
      <waitfor>
        <channel name="IsLocked" value="true"/>
      </waitfor>
    </else>
  </if>
  <!-- lock device strongly -->
  <set id="lockStrong">
    <behavior require="isLocked"/>
    <channel name="LockStrong" value="true"/>
  </set>
  
  <!-- Now tester is prepared, mirror is fixed -->
  
  <!-- move calibrators up so calibration may start -->  
  <set id="moveCalibUp">
    <behavior require="lockStrong"/>
    <channel name="MoveDistanceSensorDown" value="false"/>
    <channel name="MoveDistanceSensorUp" value="true"/>
  </set>
  <!-- wait for calibrators to be up -->
  <waitfor id="isCalibUp">
    <behavior require="moveCalibUp"/>
    <channel name="IsDistanceSensorUp" value="true"/>
  </waitfor>
  <!-- wait one second -->
  <wait id="waitSecond" time="00:00:01">
    <behavior require="isCalibUp"/>
  </wait>
  <!-- allow mirror to move -->
  <set id="allowMovement">
    <behavior require="waitSecond"/>
    <channel name="AllowMirrorMovement" value="true"/>
  </set>
  
  <!-- Now calibration may start -->
  <calib id="calibration">
    <!-- movement of mirror glass must be allowed -->
    <behavior require="allowMovement"/>
  </calib>

  <!-- disallow mirror to move -->
  <set>
    <behavior require="calibration"/>
    <channel name="AllowMirrorMovement" value="false"/>
  </set>
  <!-- move calibrators down -->
  <set id="moveCalibDown">
    <behavior require="calibration"/>
    <channel name="MoveDistanceSensorDown" value="true"/>
    <channel name="MoveDistanceSensorUp" value="false"/>
  </set>
  <!-- wait for calibrators to be down -->
  <waitfor id="isCalibDown">
    <behavior require="moveCalibDown"/>
    <channel name="IsDistanceSensorDown" value="true"/>
  </waitfor>

  <!-- open device -->
  <set id="unlock2">
    <behavior require="isCalibDown"/>
    <channel name="LockStrong" value="false"/>
    <channel name="LockWeak" value="false"/>
    <channel name="UnlockWeak" value="true"/>
    <channel name="UnlockStrong" value="true"/>
  </set>
  
  <!-- wait for device to be opened -->
  <if>
    <behavior require="unlock2"/>
    <channel name="IsOldMirror" value="true"/>
    <then>
      <waitfor>
        <channel name="IsOldLocked" value="true"/>
      </waitfor>
    </then>
    <else>
      <waitfor>
        <channel name="IsLocked" value="true"/>
      </waitfor>
    </else>
  </if>
</timeline>
