=== vajanko/mirror-testing-system/MTS/config/template.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!--
  This is document definition file for default template test collection.
  Use this dtd to define xml template from which graphical user interface
  will be generated.
-->

<!-- collection of test templates -->
<!ELEMENT tests (test)*>

<!-- template for a test: collection of test parameters -->
<!ELEMENT test (name, group, description?, param*)>

<!-- each defined test has a unique identifier -->
<!ATTLIST test 
          id NMTOKEN #REQUIRED
          enabled (true|false) "false">

<!ELEMENT param (name, description?, type, value, decimals?, min?, max?, unit?, values?)>
<!ATTLIST param
          id NMTOKEN #REQUIRED
          type (int|double|bool|string|enum) "string"
          >

<!-- sub elements of parameters (or tests) -->
<!ELEMENT name (#PCDATA)>           <!-- name of test or parameter -->
<!ELEMENT description (#PCDATA)>    <!-- description of test of parameter -->
<!ELEMENT type (#PCDATA)>           <!-- type of parameter value -->
<!ELEMENT value (#PCDATA)>          <!-- default parameter value or possible value (if enumerator) -->
<!ELEMENT min (#PCDATA)>            <!-- min possible parameter value (if numeric) -->
<!ELEMENT max (#PCDATA)>            <!-- max possible parameter value (if numeric) -->
<!ELEMENT decimals (#PCDATA)>       <!-- number of displayed decimals of parameter value (if numeric) -->
<!ELEMENT unit EMPTY>               <!-- unit of parameter value (if numeric) -->
<!ELEMENT values (value+)>          <!-- list of possible parameters values (if enumerator) -->

<!ELEMENT group (#PCDATA)>          <!-- each test belongs to particular group of tests -->

<!ATTLIST unit type (none|miliseconds|seconds|miliampheres|degrees|volts|milimeters) "none">

=== vajanko/mirror-testing-system/MTS/config/template.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE tests SYSTEM "template.dtd">

<tests>
  <!-- Informative parameters about test collection -->
  <test id="Info">
    <name>Information</name>
    <group>Informative Settings</group>
    <description>This setting will not be used for testing.</description>
    <param id="orientation">
      <name>Orientation</name>
      <description></description>
      <type>enum</type>
      <value>0</value>      <!-- index of selected value -->
      <values>
        <value>Left</value>
        <value>Right</value>
      </values>
    </param>
    <param id="partNumber">
      <name>Part Number</name>
      <description></description>
      <type>string</type>
      <value></value>
    </param>
    <param id="supplierName">
      <name>Supplier Name</name>
      <description></description>
      <type>string</type>
      <value></value>      
    </param>
    <param id="description">
      <name>Description</name>
      <description></description>
      <type>string</type>
      <value></value>
    </param>
  </test>
  
  <!-- Tear test -->
  <test id="TearTest" enabled="true">
    <name>Tear Glass Test</name>
    <group>Other</group>
    <description></description>
    <param id="TestingTime">
      <name>Testing Time</name>
      <description>Time of glass tearing out</description>
      <type>double</type>
      <value>2.5</value>
      <min>0</min>
      <max>20</max>
      <unit type="miliseconds"/>
    </param>
  </test>        
  
  <!-- Travel tests -->
  <test id="TravelEast">
    <name>Travel East</name>
    <group>Travel Tests</group>
    <description></description>
    <param id="MinAngle">
      <name>Min angle</name>
      <description></description>
      <type>double</type>
      <value>5.0</value>
      <min>0</min>
      <max>15</max>
      <unit type="degrees"/>
    </param>
    <param id="MaxCurrent">
      <name>Max current</name>
      <description></description>
      <type>int</type>
      <value>200</value>
      <min>0</min>
      <max>2000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="MaxOverloadTime">
      <name>Max overload time</name>
      <description></description>
      <type>int</type>
      <value>500</value>
      <min>0</min>
      <max>5000</max>
      <unit type="miliseconds"/>
    </param>
  </test>
  <test id="TravelWest">
    <name>Travel West</name>
    <group>Travel Tests</group>
    <description></description>
    <param id="MinAngle">
      <name>Min angle</name>
      <description></description>
      <type>double</type>
      <value>5.0</value>
      <min>0</min>
      <max>15</max>
      <unit type="degrees"/>
    </param>
    <param id="MaxCurrent">
      <name>Max current</name>
      <description></description>
      <type>int</type>
      <value>200</value>
      <min>0</min>
      <max>2000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="MaxOverloadTime">
      <name>Max overload time</name>
      <description></description>
      <type>int</type>
      <value>500</value>
      <min>0</min>
      <max>5000</max>
      <unit type="miliseconds"/>
    </param>
  </test>
  <test id="TravelSouth">
    <name>Travel South</name>
    <group>Travel Tests</group>
    <description></description>
    <param id="MinAngle">
      <name>Min angle</name>
      <description></description>
      <type>double</type>
      <value>5.0</value>
      <min>0</min>
      <max>15</max>
      <unit type="degrees"/>
    </param>
    <param id="MaxCurrent">
      <name>Max current</name>
      <description></description>
      <type>int</type>
      <value>200</value>
      <min>0</min>
      <max>2000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="MaxOverloadTime">
      <name>Max overload time</name>
      <description></description>
      <type>int</type>
      <value>500</value>
      <min>0</min>
      <max>5000</max>
      <unit type="miliseconds"/>
    </param>
  </test>
  <test id="TravelNorth">
    <name>Travel North</name>
    <group>Travel Tests</group>
    <description></description>
    <param id="MinAngle">
      <name>Min angle</name>
      <description></description>
      <type>double</type>
      <value>5.0</value>
      <min>0</min>
      <max>15</max>
      <unit type="degrees"/>
    </param>
    <param id="MaxCurrent">
      <name>Max current</name>
      <description></description>
      <type>int</type>
      <value>200</value>
      <min>0</min>
      <max>2000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="MaxOverloadTime">
      <name>Max overload time</name>
      <description></description>
      <type>int</type>
      <value>500</value>
      <min>0</min>
      <max>5000</max>
      <unit type="miliseconds"/>
    </param>
  </test>

  <!-- Current tests -->
  <test id="Powerfold">
    <name>Powerfold</name>
    <group>Current Tests</group>
    <description></description>
    <param id="Presence">
      <name>Test presence</name>
      <description></description>
      <type>bool</type>
      <value>true</value>
    </param>
    <param id="MaxCurrent">
      <name>Max current</name>
      <description></description>
      <type>int</type>
      <value>200</value>
      <min>0</min>
      <max>4000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="MaxOverloadTime">
      <name>Max overload time</name>
      <description></description>
      <type>int</type>
      <value>200</value>
      <min>0</min>
      <max>5000</max>
      <unit type="miliseconds"/>
    </param>
    <param id="MaxTestingTime">
      <name>Max testing time</name>
      <description></description>
      <type>double</type>
      <value>3</value>
      <min>0</min>
      <max>10</max>
      <unit type="seconds"/>
    </param>
  </test>
  <test id="HeatingFoil">
    <name>Heating Foil</name>
    <group>Current Tests</group>
    <description></description>
    <param id="Presence">
      <name>Test presence</name>
      <description></description>
      <type>bool</type>
      <value>true</value>      
    </param>
    <param id="MinCurrent">
      <name>Min Current</name>
      <description></description>
      <type>int</type>
      <value>100</value>
      <min>0</min>
      <max>4000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="MaxCurrent">
      <name>Max Current</name>
      <description></description>
      <type>int</type>
      <value>200</value>
      <min>0</min>
      <max>4000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="TestingTime">
      <name>Testing Time</name>
      <description></description>
      <type>double</type>
      <value>2.5</value>
      <min>0</min>
      <max>20</max>
      <unit type="miliseconds"/>
    </param>
  </test>
  <test id="DirectionLight">
    <name>Direction Light</name>
    <group>Current Tests</group>
    <description></description>
    <param id="Presence">
      <name>Test presence</name>
      <description></description>
      <type>bool</type>
      <value>true</value>
    </param>
    <param id="MinCurrent">
      <name>Min Current</name>
      <description></description>
      <type>int</type>
      <value>100</value>
      <min>0</min>
      <max>4000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="MaxCurrent">
      <name>Max Current</name>
      <description></description>
      <type>int</type>
      <value>200</value>
      <min>0</min>
      <max>4000</max>
      <unit type="miliampheres"/>
    </param>
    <param id="BlinksCount">
      <name>Number of Blinks</name>
      <description></description>
      <type>int</type>
      <value>2</value>
      <min>1</min>
      <max>10</max>
      <unit type="none"/>
    </param>
    <param id="LightingTime">
      <name>Lighting Time</name>
      <description></description>
      <type>double</type>
      <value>1.5</value>
      <min>0</min>
      <max>5</max>
      <unit type="seconds"/>
    </param>
    <param id="BreakTime">
      <name>Break Time</name>
      <description></description>
      <type>double</type>
      <value>1.5</value>
      <min>0</min>
      <max>5</max>
      <unit type="seconds"/>
    </param>
  </test>
  
  <!-- Presence test -->
  <test id="Rubber">
    <name>Rubber</name>
    <group>Presence Tests</group>
    <description>Test presence of rubber</description>
    <param id="Presence">
      <name>Is present</name>
      <description>If enabled rubber should be present</description>
      <type>bool</type>
      <value>true</value>
    </param>
  </test>
  <test id="MirrorGlass">
    <name>Mirror Glass</name>
    <group>Presence Tests</group>
    <description>Test presence of mirror glass</description>
    <param id="Presence">
      <name>Is present</name>
      <description>If enabled mirror glass should be present</description>
      <type>bool</type>
      <value>true</value>
    </param>
  </test>
        
</tests>
