=== vajanko/mirror-testing-system/MTS/config/tests.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT timeline (set|wait|waitfor|setmulti|if|check|test)*>

<!-- set channel value -->
<!ELEMENT set EMPTY>
<!ATTLIST set id ID #IMPLIED
              type (allow|disallow) "allow"
              tasks IDREFS #IMPLIED
              channel NMTOKEN #REQUIRED
              value (true|false) #REQUIRED>
<!-- wait for a specified period of time -->
<!ELEMENT wait EMPTY>
<!ATTLIST wait id ID #IMPLIED
               type (allow|disallow) "allow"
               tasks IDREFS #IMPLIED
               time CDATA #REQUIRED>
<!-- wait for specified value on a specified channel -->
<!ELEMENT waitfor EMPTY>
<!ATTLIST waitfor id ID #IMPLIED
                  type (allow|disallow) "allow"
                  tasks IDREFS #IMPLIED
                  channel NMTOKEN #REQUIRED
                  value (true|false) #REQUIRED>
<!-- set multiple channels values -->
<!ELEMENT setmulti (channel)+>
<!ATTLIST setmulti id ID #IMPLIED
                   type (allow|disallow) "allow"
                   tasks IDREFS #IMPLIED>
<!ELEMENT channel EMPTY>
<!ATTLIST channel name NMTOKEN #REQUIRED
                  value (true|false) #REQUIRED>
<!-- condition task -->
<!ELEMENT if (then,else?)>
<!ATTLIST if id ID #IMPLIED
             type (allow|disallow) "allow"
             tasks IDREFS #IMPLIED
             channel NMTOKEN #REQUIRED
             value (true|false) #REQUIRED>
<!ELEMENT then (set|wait|waitfor|setmulti|if|check|test)>
<!ELEMENT else (set|wait|waitfor|setmulti|if|check|test)?>

<!-- check (usually presence) test -->
<!ELEMENT check EMPTY>
<!ATTLIST check id ID #REQUIRED
                testparam NMTOKEN #REQUIRED
                channel NMTOKEN #REQUIRED
                value (true|false) #REQUIRED>

<!-- test -->
<!ELEMENT test EMPTY>
<!ATTLIST test id ID #REQUIRED
               type (allow|disallow) "allow"
               tasks IDREFS #IMPLIED
               testtype NMTOKEN #REQUIRED
               testparam NMTOKEN #REQUIRED>


<!-- center mirror glass -->
<!ELEMENT center EMPTY>
<!ATTLIST center id NMTOKEN #REQUIRED>

=== vajanko/mirror-testing-system/MTS/config/tests.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE timeline SYSTEM "tests.dtd">

<timeline>
  <!-- allow to switch power supply on -->
  <set channel="AllowPowerSupply" value="true"/>
  <!-- wait for power supply to switched on -->
  <waitfor channel="IsPowerSupplyOff" value="false"/>
  <!-- open device if it is closed -->
  <if channel="IsOldMirror" value="true">
    <then>
      <if channel="IsOldLocked" value="true">
        <then>
          <setmulti>
            <channel name="LockStrong" value="false"/>
            <channel name="LockWeak" value="false"/>
            <channel name="UnlockWeak" value="true"/>
            <channel name="UnlockStrong" value="true"/>
          </setmulti>
        </then>
      </if>
    </then>
    <else>
      <if channel="IsLocked" value="true">
        <then>
          <setmulti>
            <channel name="LockStrong" value="false"/>
            <channel name="LockWeak" value="false"/>
            <channel name="UnlockWeak" value="true"/>
            <channel name="UnlockStrong" value="true"/>
          </setmulti>
        </then>
      </if>
    </else>
  </if>
  <!-- wait for start button to be pressed and released -->
  <waitfor channel="IsStartPressed" value="true"/>
  <waitfor channel="IsStartPressed" value="false"/>
  <!-- switch off all lights (from previous sequence) -->
  <setmulti type="disallow" id="lightsOff">
    <channel name="GreenLightOn" value="false"/>
    <channel name="RedLightOn" value="false"/>
  </setmulti>
  <!-- close device -->
  <setmulti type="allow" tasks="lightsOff">
    <channel name="LockStrong" value="false"/>
    <channel name="LockWeak" value="true"/>
    <channel name="UnlockWeak" value="false"/>
    <channel name="UnlockStrong" value="false"/>
  </setmulti>
  <!-- wait for device to be closed -->
  <if channel="IsOldMirror" value="true">
    <then>
      <waitfor channel="IsOldLocked" value="true"/>
    </then>
    <else>
      <waitfor channel="IsLocked" value="true"/>
    </else>
  </if>
  <!-- lock device strongly -->
  <set channel="LockStrong" value="true"/>

  <!--<test testparam="Pulloff" testtype="PulloffTest" id="pulloff"/>-->
  
  <test testparam="Powerfold" testtype="PowerfoldTest" id="powerfold" type="disallow"/>
  <test testparam="DirectionLight" testtype="DirectionLightTest" id="directionLight" type="disallow"/>
  <test testparam="HeatingFoil" testtype="HeatingFoilTest" id="heatingFoil" type="disallow"/>
  
  <!-- move calibrators up -->
  <setmulti>
    <channel name="MoveDistanceSensorDown" value="false"/>
    <channel name="MoveDistanceSensorUp" value="true"/>
  </setmulti>
  <!-- wait for calibrators to be up -->
  <waitfor channel="IsDistanceSensorUp" value="true"/>
  <!-- wait one second -->
  <wait time="00:00:01"/>
  <!-- allow mirror to move -->
  <set channel="AllowMirrorMovement" value="true"/>

  <test testparam="TravelNorth" testtype="TravelNorthTest" id="travelNorth"/>
  <test testparam="TravelSouth" testtype="TravelSouthTest" id ="travelSouth"/>
  <test testparam="TravelEast" testtype="TravelEastTest" id ="travelEast"/>
  <test testparam="TravelWest" testtype="TravelWestTest" id ="travelWest"/>

  <!-- disallow mirror to move -->
  <set channel="AllowMirrorMovement" value="false" type="disallow"/>
  <!-- move calibrators down -->
  <setmulti type="disallow">
    <channel name="MoveDistanceSensorDown" value="true"/>
    <channel name="MoveDistanceSensorUp" value="false"/>
  </setmulti>
  <!-- wait for calibrators to be down -->
  <waitfor channel="IsDistanceSensorDown" value="true"/>

  <!-- open device -->
  <if channel="IsOldMirror" value="true">
    <then>
      <if channel="IsOldLocked" value="true">
        <then>
          <setmulti>
            <channel name="LockStrong" value="false"/>
            <channel name="LockWeak" value="false"/>
            <channel name="UnlockWeak" value="true"/>
            <channel name="UnlockStrong" value="true"/>
          </setmulti>
        </then>
      </if>
    </then>
    <else>
      <if channel="IsLocked" value="true">
        <then>
          <setmulti>
            <channel name="LockStrong" value="false"/>
            <channel name="LockWeak" value="false"/>
            <channel name="UnlockWeak" value="true"/>
            <channel name="UnlockStrong" value="true"/>
          </setmulti>
        </then>
      </if>
    </else>
  </if>
  <!-- wait for device to be opened -->
  <if channel="IsOldMirror" value="true">
    <then>
      <waitfor channel="IsOldLocked" value="true"/>
    </then>
    <else>
      <waitfor channel="IsLocked" value="true"/>
    </else>
  </if>
</timeline>
